### ISSUE TITLE
Failed to activate the epitech-norm package

### ISSUE THREAD

**Issue by newfr** [matthieukern/atom-epitech-norm#3]
I have only launch atom. And since the update it provoque this. Whit this bug i can't make a newline.

**Atom Version**: 0.199.0
**System**: linux 3.19.5-200.fc21.x86_64
**Thrown From**: [epitech-norm](https://github.com/matthieukern/atom-epitech-norm) package, v0.3.0

### Stack Trace

Failed to activate the epitech-norm package

```
At Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at new EpitechNorm (/home/ganter_v/.atom/packages/epitech-norm/lib/epitech-norm.coffee:13:35)
    at /home/ganter_v/.atom/packages/epitech-norm/lib/main.coffee:25:18
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:267:9)
    at Object.module.exports.activate (/home/ganter_v/.atom/packages/epitech-norm/lib/main.coffee:19:22)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:238:19)
    at /usr/share/atom/resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:435:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:419:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "graphite-ui",
      "magneto-syntax"
    ],
    "projectHome": "/usr/media/suse/ganter_v/rendu/"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.6.9
epitech-headers, v0.2.7
epitech-norm, v0.3.0
graphite-ui, v0.14.1
linter, v0.12.2
linter-clang, v2.25.1
magneto-syntax, v0.3.0
symbols-tree-view, v0.9.2

# Dev
No dev packages
```

**Comment by matthieukern** [comment]
Impossible to reproduce on Atom 1.1.0

**Comment by antoinegergy** [comment]
Same bug  on Atom 1.1.0 when files are already open on startup 

OS: Debian (Kali 2.0)
Atom 1.1.0

**Comment by matthieukern** [comment]
Ok I will look

**Comment by Arignir** [comment]
Same bug here :/

**Comment by Arignir** [comment]
By the way, the identation bugs when we have multiples if() of one line in a row.

Ex:

if ()
  if()
    stg;
stg2;

stg2 will be badly indented.

**Comment by yoahnl** [comment]
Same problem with OS X...

**Comment by IniterWorker** [comment]
The __split bug__ is solved.

**Comment by Mortimr** [comment]
Hey , having the split issue too on atom 1.3.2 (Archlinux) ! :(

**Comment by IniterWorker** [comment]
Just because matthieu kern is late.

```
cd ~/.atom/packages
git clone git@github.com:matthieukern/atom-epitech-norm.git
```

Remove the first plugin or unplug on atom editor.

**Comment by AxelLavielle** [comment]
up on the subject, the bug is still there and sooooooooo awful.

**Comment by Arignir** [comment]
AxelLavielle: What is your version  of Atom ? And epitech-norm ? On recent versions, the "split" bug is no more present.

**Comment by AxelLavielle** [comment]
It's okay now, after uninstall/reinstall of atom-epitech-norm, I probably didn't have the last version, thank's

________________________________
De : Benjamin Grange <notifications@github.com>
Envoyé : vendredi 10 juin 2016 19:04:37
À : matthieukern/atom-epitech-norm
Cc : axel lavielle; Comment
Objet : Re: [matthieukern/atom-epitech-norm] Failed to activate the epitech-norm package (#3)


AxelLavielle: What is your version of Atom ? And epitech-norm ? On recent versions, the "split" bug is no more present.

-

**Comment by AxelLavielle** [comment]
I recreated the issue again ! I have the split bug when there is an untitled empty file open in atom. To fix it, I just close the untitled file and restart atom and everything is okay then. Not that important to fix so !
![sans titre](https://cloud.githubusercontent.com/assets/12008266/16143168/4968da3c-346b-11e6-8fd8-991cea7aaf58.png)

**Comment by IniterWorker** [comment]
To prevent this split bug, juste catch the undefined element. But, In my push, i had corrected this bug. I think Mathieu haven't push on atom package.
